### ISSUE TITLE
Enhance error handling in poller

### ISSUE THREAD

**Issue by douginator2000** [qiime/qiime_web_app#19]
The poller seems to die fairly easily. Add better error handling to allow it's continued operation when exceptions are thrown.

**Comment by wasade** [comment]
last week was essentially the first i've heard of this: please send on tracebacks

**Comment by douginator2000** [comment]
The main issue seems to be that most exceptions cause the poller to exit. I
think that at a minimum, if the main block of code were wrapped such that
it can continue executing it would be sufficient.

On Tue, Oct 23, 2012 at 10:02 AM, Daniel McDonald
notifications@github.comwrote:

> last week was essentially the first i've heard of this: please send on
> tracebacks
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/issues/19#issuecomment-9707544.

## 

Doug Wendel, PRA
University of Colorado at Boulder
Department of Chemistry and Biochemistry
Knight Lab

**Comment by wasade** [comment]
I'd prefer direct error handling, not blanket handling. Below are the tracebacks with comments inline

Traceback (most recent call last):
  File "TorqueOraPoller/poller.py", line 330, in <module>
    daemon.restart()
  File "/home/wwwuser/projects/Qiime/qiime_web_app/python_code/TorqueOraPoller/daemon.py", line 192, in restart
    self.start()
  File "/home/wwwuser/projects/Qiime/qiime_web_app/python_code/TorqueOraPoller/daemon.py", line 120, in start
    self.run()
  File "TorqueOraPoller/poller.py", line 103, in run
    self.updateMyJobs(err_jobs)
  File "TorqueOraPoller/poller.py", line 209, in updateMyJobs
    new_state = self._job_completed_or_errored(job)
  File "TorqueOraPoller/poller.py", line 169, in _job_completed_or_errored
    stdout_lines = self._readfile(self.home, job_name, pbs_id, 'stdout')
  File "TorqueOraPoller/poller.py", line 144, in _readfile
    filename = '%s/%s/%d.o%s' % (home,qiime_job, job_name, pbs_job_id)
NameError: global name 'qiime_job' is not defined

This stemmed from someone modifying but not testing the code, and this change was never checked in.

Traceback (most recent call last):
  File "TorqueOraPoller/poller.py", line 330, in <module>
    daemon.restart()
  File "/home/wwwuser/projects/Qiime/qiime_web_app/python_code/TorqueOraPoller/daemon.py", line 192, in restart
    self.start()
  File "/home/wwwuser/projects/Qiime/qiime_web_app/python_code/TorqueOraPoller/daemon.py", line 120, in start
    self.run()
  File "TorqueOraPoller/poller.py", line 103, in run
    self.updateMyJobs(err_jobs)
  File "TorqueOraPoller/poller.py", line 227, in updateMyJobs
    for job_name, new_state, notes in state_feedback:
ValueError: need more than 2 values to unpack

This one is addressed in the pending pull request.

Traceback (most recent call last):
  File "TorqueOraPoller/poller.py", line 327, in <module>
    daemon.start()
  File "/home/wwwuser/projects/Qiime/qiime_web_app/python_code/TorqueOraPoller/daemon.py", line 120, in start
    self.run()
  File "TorqueOraPoller/poller.py", line 104, in run
    self.updateMyJobs(err_jobs)
  File "TorqueOraPoller/poller.py", line 203, in updateMyJobs
    poll_result = self.parseQstat(output)
  File "TorqueOraPoller/poller.py", line 130, in parseQstat
    job_id, job_name, user, cput, state, queue = line.strip().split()
ValueError: need more than 3 values to unpack

I can't identify this right now, so I added in more verbose error throwing so that we can address this if it comes up in the future. It will handle this gracefully now though

Traceback (most recent call last):
  File "qiime_web_app/python_code/TorqueOraPoller/poller.py", line 336, in <module>
    daemon.restart()
  File "/home/wwwuser/projects/Qiime/qiime_web_app/python_code/TorqueOraPoller/daemon.py", line 192, in restart
    self.start()
  File "/home/wwwuser/projects/Qiime/qiime_web_app/python_code/TorqueOraPoller/daemon.py", line 120, in start
    self.run()
  File "qiime_web_app/python_code/TorqueOraPoller/poller.py", line 99, in run
    new_jobs = self.checkForNewJobs()
  File "qiime_web_app/python_code/TorqueOraPoller/poller.py", line 244, in checkForNewJobs
    cursor.callproc('get_new_torque_jobs',[jobs_cursor])
cx_Oracle.OperationalError: ORA-03113: end-of-file on communication channel
Process ID: 6683
Session ID: 131 Serial number: 15569

Doug, does this make sense to you? I haven't added in a check yet, but I can handle this gracefully

Traceback (most recent call last):
  File "/home/wwwuser/projects/Qiime/qiime_web_app/python_code/TorqueOraPoller/poller.py", line 332, in <module>
  File "/home/wwwuser/projects/Qiime/qiime_web_app/python_code/TorqueOraPoller/daemon.py", line 120, in start
  File "/home/wwwuser/projects/Qiime/qiime_web_app/python_code/TorqueOraPoller/poller.py", line 99, in run
  File "/home/wwwuser/projects/Qiime/qiime_web_app/python_code/TorqueOraPoller/poller.py", line 244, in checkForNewJobs
cx_Oracle.OperationalError: ORA-01089: immediate shutdown in progress - no operations are permitted
Process ID: 31469
Session ID: 376 Serial number: 63928

...not sure what we should do here...

Looking through this, it appears the poller has only crashed 15 times since we started running it. Which isn't horrible given that its been up for a few years essentially no error handling (intentionally).
